media: media
content:
  - name: pages
    label: Contenuti
    type: collection
    path: content/porri
    fields:
      - name: title
        type: string
      - name: subtitle
        type: string
      - name: body
        type: rich-text
  - name: jap
    label: Giappone inondato
    type: collection
    path: content/jap
    fields:
      - name: title
        type: string
      - name: subtitle
        type: string
      - name: body
        type: rich-text
  - name: site
    label: Site settings (Hugo)
    type: file
    path: hugo.toml
    