media: media
content:
  - name: pages
    label: Contenuti
    type: collection
    path: content/porri
    fields:
      - name: Title
        type: string
      - name: Subtitle
        type: string
      - name: Body
        type: rich-text