media: media
content:
  - name: pages
    label: Contenuti
    type: collection
    path: content/porri
    fields:
      - name: title
        type: string
      - name: subtitle
        type: string
      - name: body
        type: rich-text